export const ADD_VENUE_SUCCESS = 'ADD_VENUE_SUCCESS';
export const REMOVE_VENUE_SUCCESS = 'REMOVE_VENUE_SUCCESS';
export const SELECT_VENUE_SUCCESS = 'SELECT_VENUE_SUCCESS';
export const REMOVENAME_VENUE_SUCCESS = 'REMOVENAME_VENUE_SUCCESS';
